general:
  use-webhooks: false
  collect-billing-address: true
storage:
  mysql:
    use: false
    ip: "localhost"
    port: 3306
    database: "magmapay"
    username: "root"
    password: "password"
  sqlite:
    use: true
    url: "jdbc:sqlite:plugins/MagmaPay/MagmaPay.db"
methods:
  stripe:
    api-key: "xx"
messages:
  create-user:
    prompts:
      enter-email: "&8MagmaPay &7>> &8Enter your e-mail address:"
      enter-pin: "&8MagmaPay &7>> &8Enter a 4-digit pin:"
      enter-address: "&8MagmaPay &7>> &8Enter your street address:"
      enter-city: "&8MagmaPay &7>> &8Enter your city:"
      enter-state: "&8MagmaPay &7>> &8Enter your state or province (NA if not applicable):"
      enter-zip: "&8MagmaPay &7>> &8Enter your zip code (NA if not applicable):"
      enter-country: "&8MagmaPay &7>> &8Enter your country:"
      enter-card-name: "&8MagmaPay &7>> &8Enter your credit card's cardholder name:"
      enter-card-number: "&8MagmaPay &7>> &8Enter your credit card number:"
      enter-card-month: "&8MagmaPay &7>> &8Enter your card's expiry month (ex: 05):"
      enter-card-year: "&8MagmaPay &7>> &8Enter your card's expiry year (ex: 20 or 2020):"
      enter-card-cvc: "&8MagmaPay &7>> &8Enter your card's CVC (3 digits on back of card):"
      creating-user: "&8MagmaPay &7>> &8Creating user, please wait..."
      user-created: "&8MagmaPay &7>> User created successfully."
      quit-successful: "&8MagmaPay &7>> You have successfully quit the user creation process."
    errors:
      validation-error: "&8MagmaPay &7>> &8Our payment processor could not validate your information: &7<error>"
      stripe-error: "&8MagmaPay &7>> &8An error occurred: &7<error>"
      invalid-email: "&8MagmaPay &7>> &8You entered an invalid email, creation cancelled."
      invalid-pin: "&8MagmaPay &7>> &8You entered an invalid pin, creation cancelled."
  pin-retrieval:
    prompts:
      enter-pin: "&8MagmaPay &7>> &8You initiated a charge, enter your pin to confirm it:"
      cancel-successful: "&8MagmaPay &7>> You have successfully cancelled the pending charge."