config-version: 1
storage:
  mysql:
    use: false
    ip: "localhost"
    port: 3306
    database: "magmapay"
    username: "root"
    password: "password"
  sqlite:
    use: true
    url: "jdbc:sqlite:plugins/MagmaPay/MagmaPay.db"
methods:
  stripe:
    api-key: "xx"
messages:
  create-user:
    prompts:
      enter-email: "&8MagmaPay &7>> &8Enter your e-mail address:"
      enter-pin: "&8MagmaPay &7>> &8Enter a 4-digit pin:"
      creating-user: "&8MagmaPay &7>> &8Creating user, please wait..."
      user-created: "&8MagmaPay &7>> User created successfully."
    errors:
      stripe-error: "&8MagmaPay &7>> &8An error occurred: &7<error>"
      invalid-email: "&8MagmaPay &7>> &8You entered an invalid email, creation cancelled."
      invalid-pin: "&8MagmaPay &7>> &8You entered an invalid pin, creation cancelled."
  pin-retrieval:
    prompts:
      enter-pin: "&8MagmaPay &7>> &8You initiated a charge, enter your pin to confirm it:"