config-version: 1
storage:
  mysql:
    use: true
    ip: "localhost"
    port: 3306
    database: "magmapay"
    username: "root"
    password: "password"
  sqlite:
    use: true
    url: "jdbc:sqlite:plugins/MagmaPay/MagmaPay.db"
messages:
  create-user:
    enter-email: "&8MagmaPay &7>> &8Enter your e-mail address:"
    enter-pin: "&8MagmaPay &7>> &8Enter a 4-digit pin:"